In [1]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris.x = iris.data
iris.y = iris.target

In [2]:
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
x_train, x_test, y_train, y_test = train_test_split(iris.x, iris.y, 
                                                       train_size=0.8, random_state=0)

In [3]:
from sklearn import svm
svm_model = svm.SVC()

In [4]:
from sklearn.model_selection import GridSearchCV
grid_para_svm = [{'C': [1, 10, 100, 1000], 'kernel': ['poly'], 'degree': [2, 3, 4]}, \
                 {'C': [1, 10, 100, 1000], 'kernel': ['linear']}, \
                 {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}]

In [5]:
grid_search_svm = GridSearchCV(svm_model, grid_para_svm, scoring = 'accuracy', cv=5)
grid_search_svm.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'degree': [2, 3, 4],
                          'kernel': ['poly']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             scoring='accuracy')

In [6]:
grid_search_svm.best_params_

{'C': 1, 'degree': 4, 'kernel': 'poly'}

In [7]:
grid_search_svm.best_score_ # cv accuracy

0.9666666666666666

In [9]:
pred=grid_search_svm.predict(x_train)
import sklearn.metrics as sm
sm.confusion_matrix(pred,y_train)

array([[39,  0,  0],
       [ 0, 35,  1],
       [ 0,  2, 43]])

In [10]:
sm.accuracy_score(pred,y_train) # accuracy score

0.975

In [11]:
pred=grid_search_svm.predict(x_test)
import sklearn.metrics as sm
sm.confusion_matrix(pred,y_test)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]])

In [12]:
sm.accuracy_score(pred,y_test)

1.0

In [14]:
# support vectors.
svm_model = svm.SVC(C=1, degree=4, kernel='poly')
svm_model.fit(x_train, y_train)

SVC(C=1, degree=4, kernel='poly')

In [15]:
svm_index = svm_model.support_ # row index of support vector
print (svm_index)

[ 61  81   1   7  47 102 103 111   3  18  24  25  26  68  89]


In [16]:
len(svm_index)

15

In [17]:
support = svm_model.support_vectors_ # value of support vector
print (support)

[[4.5 2.3 1.3 0.3]
 [5.1 3.3 1.7 0.5]
 [5.4 3.  4.5 1.5]
 [6.  2.7 5.1 1.6]
 [5.1 2.5 3.  1.1]
 [6.3 2.5 4.9 1.5]
 [6.7 3.  5.  1.7]
 [5.9 3.2 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.  2.2 5.  1.5]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [7.2 3.  5.8 1.6]
 [6.  3.  4.8 1.8]]
