In [1]:
# build a neural network
# AND gate
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 0.09
weight2 = 0.09
bias = -0.1

# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', 
                                              ' Linear Combination', 
                                              '  Activation Output',
                                              '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

 Input 1    Input 2   Linear Combination    Activation Output   Is Correct
       0          0                -0.10                    0          Yes
       0          1                -0.01                    0          Yes
       1          0                -0.01                    0          Yes
       1          1                 0.08                    1          Yes


In [2]:
# NOT and gate
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = xx
weight2 = xx
bias = xx

# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, True, True, False]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', 
                                              '  Linear Combination', 
                                              '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))


You got 1 wrong.  Keep trying!

 Input 1    Input 2    Linear Combination    Activation Output   Is Correct
       0          0                  0.10                    1          Yes
       0          1                 -0.10                    0           No
       1          0                  0.12                    1          Yes
       1          1                 -0.08                    0          Yes


In [3]:
#Simple network: sigmoid function to make a prediction
import numpy as np

def sigmoid(x):
    # TODO: Implement sigmoid function
    return 1/(1+np.exp(-x))

inputs = np.array([0.7, -0.3])
weights = np.array([0.1, 0.8])
bias = -0.1

# TODO: Calculate the output
output = sigmoid(np.dot(weights, inputs)+ bias)

print('Output:')
print(output) # probability of being class 1

Output:
0.4329070950345457


In [31]:
# gradient descent to change the weight
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

# Initial weights and bias
w = np.array([0.5, -0.5, 0.3, 0.1])
b = 0.1

### Calculate one gradient descent step for each weight
### Note: Some steps have been consilated, so there are
###       fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights
h = np.dot(x, w)

# TODO: Calculate output of neural network
nn_output = sigmoid(h+b)

# TODO: Calculate error of neural network
error =0.5*((nn_output-y)**2)

# TODO: Calculate the error term
#       Remember, this requires the output gradient, which we haven't
#       specifically added a variable for.
error_term = error*sigmoid_prime(h)

# TODO: Calculate change in weights
del_w = learnrate*error_term*x

print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)
print(w+del_w)

Neural Network output:
0.7109495026250039
Amount of Error:
0.022249846328868263
Change in Weights:
[0.00237973 0.00475946 0.00713919 0.00951892]
[ 0.50237973 -0.49524054  0.30713919  0.10951892]


In [3]:
# sklearn neural network
# It has various chemical features of different wines, all grown in the same region in Italy,
# but the data is labeled by three different possible cultivars. 
# We will try to build a model that can classify what cultivar a wine belongs to based on its 
#chemical features using Neural Networks
import pandas as pd
wine = pd.read_csv('wine.data', names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", 
                                         "Alcalinity_of_Ash", "Magnesium", "Total_phenols", 
                                         "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins",
                                         "Color_intensity", "Hue", "OD280", "Proline"])

In [4]:
wine.shape

(178, 14)

In [5]:
wine.dtypes

Cultivator                int64
Alchol                  float64
Malic_Acid              float64
Ash                     float64
Alcalinity_of_Ash       float64
Magnesium                 int64
Total_phenols           float64
Falvanoids              float64
Nonflavanoid_phenols    float64
Proanthocyanins         float64
Color_intensity         float64
Hue                     float64
OD280                   float64
Proline                   int64
dtype: object

In [6]:
wine.head()

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1   14.23        1.71  2.43               15.6        127   
1           1   13.20        1.78  2.14               11.2        100   
2           1   13.16        2.36  2.67               18.6        101   
3           1   14.37        1.95  2.50               16.8        113   
4           1   13.24        2.59  2.87               21.0        118   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [7]:
wine.describe().transpose()

count        mean         std     min       25%  \
Cultivator            178.0    1.938202    0.775035    1.00    1.0000   
Alchol                178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Alcalinity_of_Ash     178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_phenols         178.0    2.295112    0.625851    0.98    1.7425   
Falvanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Cultivator              2.000    3.0000     3.00  
Alchol                 13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Alcalinity_of_Ash      19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_phenols           2.355    2.8000     3.88  
Falvanoids              2.135    2.8750     5.08  
Nonflavanoid_phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [9]:
wine.isnull().any(axis=0)

Cultivator              False
Alchol                  False
Malic_Acid              False
Ash                     False
Alcalinity_of_Ash       False
Magnesium               False
Total_phenols           False
Falvanoids              False
Nonflavanoid_phenols    False
Proanthocyanins         False
Color_intensity         False
Hue                     False
OD280                   False
Proline                 False
dtype: bool

In [15]:
X = wine.drop('Cultivator',axis=1)
y = wine['Cultivator']

In [16]:
set(y) # multiple-class classfication

{1, 2, 3}

In [10]:
wine['Cultivator'].value_counts()

2    71
1    59
3    48
Name: Cultivator, dtype: int64

In [17]:
# split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

In [18]:
# The neural network in Python may have difficulty converging before the maximum number 
#of iterations allowed if the data is not normalized. Multi-layer Perceptron is sensitive 
#to feature scaling, so it is highly recommended to scale your data. Note that you must 
#apply the same scaling to the test set for meaningful results. There are a lot of different 
#methods for normalization of data, we will use the built-in StandardScaler for standardization.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [19]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
# train the model
from sklearn.neural_network import MLPClassifier # MLPRegressor
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)
mlp.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(13, 13, 13), max_iter=500)

In [21]:
# prediction and evaluation
predictions = mlp.predict(X_test)

In [29]:
import sklearn.metrics as sm
sm.accuracy_score(y_test,predictions)

1.0

In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predictions))

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]


In [24]:
# coefs_ is a list of weight matrices, where weight matrix at index i 
# represents the weights between layer i and layer i+1.

# intercepts_ is a list of bias vectors, where the vector at index i 
# represents the bias values added to layer i+1.
len(mlp.coefs_)

4

In [26]:
mlp.coefs_ # weight

[array([[-0.56045805,  0.50389197, -0.04182295,  0.37288405, -0.58489304,
          0.30016227,  0.36061449, -0.3385583 , -0.47613741, -0.47483644,
         -0.07992364,  0.21746255, -0.12913229],
        [-0.35578154,  0.26974452, -0.36021539, -0.08689012, -0.32748639,
         -0.19770268,  0.35864261, -0.33949587, -0.02434666, -0.12649439,
         -0.56964589,  0.03499124, -0.14843846],
        [-0.41032303,  0.53415099,  0.44189009,  0.41278194, -0.26211609,
         -0.47912295,  0.33592402, -0.16149653, -0.3753309 , -0.07810315,
         -0.37706574,  0.27152471, -0.06874705],
        [ 0.17504705, -0.14151656,  0.09386767, -0.1864749 , -0.224643  ,
          0.66861659,  0.44437804,  0.50620694,  0.63521708,  0.01833292,
          0.25347363, -0.5718091 , -0.08551059],
        [-0.38851435, -0.01759612, -0.16606882, -0.12618261,  0.39363223,
         -0.27488981, -0.28357646, -0.05459729, -0.4079397 ,  0.47783   ,
         -0.29913007,  0.40362315,  0.19015561],
        [-0.488

In [27]:
mlp.intercepts_ #bias

[array([-0.14728411,  0.16278049,  0.07368504,  0.56776107, -0.14044289,
         0.04522384, -0.19198004,  0.47860733,  0.49665467, -0.1309748 ,
         0.20005109,  0.26373657,  0.1311257 ]),
 array([ 0.06919803,  0.58571053,  0.09603644, -0.04776055,  0.0562785 ,
         0.08000764,  0.2338793 ,  0.56881094,  0.1127304 ,  0.54555994,
         0.50680375, -0.12428209, -0.25909107]),
 array([-0.24098676,  0.59238292,  0.30207452, -0.3074918 ,  0.21958009,
         0.1296817 , -0.05501124, -0.31390591,  0.24122083, -0.05446165,
         0.24943495,  0.16913738,  0.20150917]),
 array([ 0.30540561, -0.48188326, -0.39348885])]